services:
  postgres:
    container_name: postgres
    image: bitnami/postgresql:latest
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: nfse-extractor
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "docker"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.13-management
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 45s
      timeout: 10s
      retries: 5

  api:
    container_name: api
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    env_file: ./apps/backend/.env
    restart: always
    ports:
      - 3000:3000 # Map host port 3000 to container port 3333
    volumes:
      - ./apps/backend:/app # Bind mount for live reloading
      - /app/node_modules # Avoid conflicts with host node_modules
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://api:3333/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  migrate:
    container_name: migrate
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    command: ["npm", "run", "migrate"]    
    depends_on:
      postgres:
        condition: service_healthy 
    networks:
      - app_network

  web:
    container_name: web
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    env_file: ./apps/frontend/.env
    restart: always
    ports:
      - 5173:5173 # Map host port 5173 to container port 5173
    volumes:
      - ./apps/frontend:/app # Bind mount for live reloading
      - /app/node_modules # Avoid conflicts with host node_modules
    networks:
      - app_network
    depends_on:
      - api

networks:
  app_network: